name: NodeJS with Webpack

on:
  push:
    branches: [ "dev-share-impl" ]
  pull_request:
    branches: [ "dev-share-impl" ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install ESLint
        run: npm install eslint

      - name: ESLint
        run: npx eslint --ext .ts,.vue .
          
