name: NodeJS with Webpack

on:
  push:
    branches: [ "dev-share-impl" ]
  pull_request:
    branches: [ "dev-share-impl" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
            - name: Infracost Actions
  # You may pin to the exact commit or the version.
  # uses: infracost/actions@0d27b734c72a1abb0aba3e2c3f54e4982cbd2591
  uses: infracost/actions@v2.1.0
  with:
    # Your Infracost API key. It can be retrieved by running `infracost configure get api_key`. We recommend using your same API key in all environments. If you don't have one, download Infracost (https://www.infracost.io/docs/#quick-start) and run `infracost auth login` to get a free API key.
    api-key: 
    # The path that will be passed to `infracost breakdown`. This may be a path to a Terraform plan JSON or a Terraform project.
    path: 
    # The behavior to use when posting cost estimate comments. Must be one of 'update' | 'delete-and-new' | 'hide-and-new' | 'new'.
    behavior: # optional, default is update
          
